package fr.gshz.hideandseek.domain.model

data class AskedQuestion(
    val uuid: String,
    val roundUuid: String,
    val category: QuestionCategory,
    val askedAt: String,
    val revealDeadlineAt: String?,
    val revealedAt: String?,
    val radarAnswer: Boolean?,
    val thermometerResult: ThermometerResult?,
    val featureType: FeatureType? = null,
    val withinMeters: Double? = null,
    val matchingAnswer: Boolean? = null,
    val transitLineLabel: String? = null,
    val measuringResult: MeasuringResult? = null,
    val tentaclesAnswer: String? = null,
    val radiusMeters: Double? = null,
    val distanceMeters: Double? = null,
    val seekerLat: Double? = null,
    val seekerLng: Double? = null,
    val startLat: Double? = null,
    val startLng: Double? = null,
    val endLat: Double? = null,
    val endLng: Double? = null,
    val photoTarget: PhotoTarget? = null,
    val status: QuestionStatus = QuestionStatus.Open,
    val replacedByUuid: String? = null,
    val replacedQuestionUuid: String? = null,
    val repeatCount: Int = 1,
    val isCustomRadius: Boolean = false,
)
