package fr.gshz.hideandseek.core.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF2B3947)
val LightOnPrimary = Color(0xFFF4F1E6)
val LightPrimaryContainer = Color(0xFFDAE2EC)
val LightOnPrimaryContainer = Color(0xFF101C2A)
val LightSecondary = Color(0xFF7F5D2B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFE2B6)
val LightOnSecondaryContainer = Color(0xFF291800)
val LightTertiary = Color(0xFFE0402E)
val LightOnTertiary = Color(0xFFFFF5F3)
val LightTertiaryContainer = Color(0xFFFFDCD8)
val LightOnTertiaryContainer = Color(0xFF3F0703)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFBF7EE)
val LightOnBackground = Color(0xFF1B1C1A)
val LightSurface = Color(0xFFFBF7EE)
val LightOnSurface = Color(0xFF1B1C1A)
val LightSurfaceVariant = Color(0xFFE2E1D5)
val LightOnSurfaceVariant = Color(0xFF44453C)
val LightOutline = Color(0xFF74756B)
val LightOutlineVariant = Color(0xFFC5C6B9)
val LightInverseSurface = Color(0xFF30312A)
val LightInverseOnSurface = Color(0xFFF0EFE3)
val LightInversePrimary = Color(0xFFAFC5DD)
val LightSurfaceDim = Color(0xFFDAD9CD)
val LightSurfaceBright = Color(0xFFFBF7EE)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF4F1E6)
val LightSurfaceContainer = Color(0xFFEFECE1)
val LightSurfaceContainerHigh = Color(0xFFE9E6DB)
val LightSurfaceContainerHighest = Color(0xFFE4E1D6)

val DarkPrimary = Color(0xFFAFC5DD)
val DarkOnPrimary = Color(0xFF1A3040)
val DarkPrimaryContainer = Color(0xFF2D3E4E)
val DarkOnPrimaryContainer = Color(0xFFDAE2EC)
val DarkSecondary = Color(0xFFF4C04C)
val DarkOnSecondary = Color(0xFF3D2800)
val DarkSecondaryContainer = Color(0xFF5D4100)
val DarkOnSecondaryContainer = Color(0xFFFFE2B6)
val DarkTertiary = Color(0xFFFFB4A9)
val DarkOnTertiary = Color(0xFF69140B)
val DarkTertiaryContainer = Color(0xFF932014)
val DarkOnTertiaryContainer = Color(0xFFFFDCD8)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF141C24)
val DarkOnBackground = Color(0xFFE9E3D6)
val DarkSurface = Color(0xFF182029)
val DarkOnSurface = Color(0xFFE9E3D6)
val DarkSurfaceVariant = Color(0xFF44453C)
val DarkOnSurfaceVariant = Color(0xFFC5C6B9)
val DarkOutline = Color(0xFF8E8F83)
val DarkOutlineVariant = Color(0xFF44453C)
val DarkInverseSurface = Color(0xFFE9E3D6)
val DarkInverseOnSurface = Color(0xFF30312A)
val DarkInversePrimary = Color(0xFF2B3947)
val DarkSurfaceDim = Color(0xFF141C24)
val DarkSurfaceBright = Color(0xFF3A414B)
val DarkSurfaceContainerLowest = Color(0xFF0F161E)
val DarkSurfaceContainerLow = Color(0xFF182029)
val DarkSurfaceContainer = Color(0xFF1C2530)
val DarkSurfaceContainerHigh = Color(0xFF26303A)
val DarkSurfaceContainerHighest = Color(0xFF313B46)

val LightAnswerContainer = Color(0xFFCFE8C0)
val LightOnAnswerContainer = Color(0xFF132A08)
val LightWarningContainer = Color(0xFFFFDCC2)
val LightOnWarningContainer = Color(0xFF3A1400)

val DarkAnswerContainer = Color(0xFF2E4A26)
val DarkOnAnswerContainer = Color(0xFFCFE8C0)
val DarkWarningContainer = Color(0xFF6B3A16)
val DarkOnWarningContainer = Color(0xFFFFDCC2)

object BrandColors {
    val hider = Color(0xFFF4C04C)
    val onHider = Color(0xFF2B3947)
    val hiderContainer = Color(0xFFFFE2B6)
    val onHiderContainer = Color(0xFF291800)

    val seeker = Color(0xFFE0402E)
    val onSeeker = Color(0xFFFFFFFF)
    val seekerContainer = Color(0xFFFFDCD8)
    val onSeekerContainer = Color(0xFF3F0703)

    val selfMarker = Color(0xFF2B3947)
    val otherMarker = Color(0xFFE0402E)
    val hidingZone = Color(0xFFF4C04C)
}
