<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260810120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add server-wide accounts table (name + password_hash), the identity anchor for players.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE public.accounts (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(80) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);');
        $this->addSql('ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);');
        $this->addSql('ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);');
        $this->addSql('CREATE UNIQUE INDEX uniq_accounts_uuid ON public.accounts USING btree (uuid);');
        $this->addSql('CREATE UNIQUE INDEX uniq_accounts_name ON public.accounts USING btree (name);');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS public.accounts CASCADE');
    }
}
