<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260808120000 extends AbstractMigration
{
    private const array SCHEMA_SQL = [
        'CREATE TABLE public.asked_questions (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    category character varying(16) NOT NULL,
    radius_meters double precision,
    seeker_point public.geography(Point,4326) DEFAULT NULL::public.geography,
    start_point public.geography(Point,4326) DEFAULT NULL::public.geography,
    end_point public.geography(Point,4326) DEFAULT NULL::public.geography,
    distance_meters double precision,
    radar_answer boolean,
    thermometer_answer character varying(16) DEFAULT NULL::character varying,
    asked_at timestamp(0) without time zone NOT NULL,
    reveal_deadline_at timestamp(0) without time zone,
    revealed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    round_id integer NOT NULL,
    asker_player_id integer NOT NULL,
    feature_type character varying(32) DEFAULT NULL::character varying,
    within_meters double precision,
    matching_answer boolean,
    measuring_answer character varying(16) DEFAULT NULL::character varying,
    tentacles_answer character varying(200) DEFAULT NULL::character varying,
    photo_target character varying(40) DEFAULT NULL::character varying,
    status character varying(16) NOT NULL,
    replaced_by_uuid character varying(36) DEFAULT NULL::character varying,
    replaced_question_uuid character varying(36) DEFAULT NULL::character varying,
    version integer DEFAULT 1 NOT NULL,
    repeat_count integer NOT NULL,
    is_custom_radius boolean DEFAULT false NOT NULL,
    transit_line_uuid character varying(36) DEFAULT NULL::character varying,
    transit_line_label character varying(255) DEFAULT NULL::character varying,
    station_name_length boolean DEFAULT false NOT NULL,
    sea_level boolean DEFAULT false NOT NULL,
    seeker_altitude double precision
);',
        'ALTER TABLE public.asked_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asked_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.chat_message_reads (
    id integer NOT NULL,
    message_id integer NOT NULL,
    player_id integer NOT NULL,
    read_at timestamp(0) without time zone NOT NULL
);',
        'ALTER TABLE public.chat_message_reads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_reads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    type character varying(16) NOT NULL,
    body character varying(2000),
    created_at timestamp(0) without time zone NOT NULL,
    game_id integer NOT NULL,
    sender_id integer,
    image_ref character varying(255) DEFAULT NULL::character varying,
    question_uuid character varying(36) DEFAULT NULL::character varying,
    reply_to_uuid character varying(36) DEFAULT NULL::character varying,
    body_key character varying(100) DEFAULT NULL::character varying,
    body_args jsonb,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);',
        'ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.features (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    feature_type character varying(32) NOT NULL,
    name character varying(200) DEFAULT NULL::character varying,
    point public.geography(Point,4326) NOT NULL,
    game_id integer NOT NULL,
    geometry text DEFAULT NULL::public.geography
);',
        'CREATE SEQUENCE public.features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'ALTER TABLE public.features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.features_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE SEQUENCE public.game_areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'CREATE TABLE public.game_areas (
    id integer DEFAULT nextval(\'public.game_areas_id_seq\'::regclass) NOT NULL,
    uuid character varying(36) NOT NULL,
    game_id integer NOT NULL,
    osm_type character varying(16) NOT NULL,
    osm_id bigint NOT NULL,
    admin_level smallint,
    name character varying(200) NOT NULL
);',
        'CREATE TABLE public.game_gtfs_lines (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    game_id integer NOT NULL,
    gtfs_source_id integer NOT NULL,
    route_id character varying(200) NOT NULL,
    ref character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    colour character varying(20) DEFAULT NULL::character varying,
    route_type character varying(30) NOT NULL,
    network character varying(255) NOT NULL,
    operator character varying(255) DEFAULT NULL::character varying
);',
        'CREATE SEQUENCE public.game_gtfs_lines_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'ALTER SEQUENCE public.game_gtfs_lines_id_seq OWNED BY public.game_gtfs_lines.id;',
        'CREATE TABLE public.game_transit_lines (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    game_id integer NOT NULL,
    osm_type character varying(16) NOT NULL,
    osm_id bigint NOT NULL,
    ref character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    colour character varying(20) DEFAULT NULL::character varying,
    route_type character varying(30) NOT NULL,
    network character varying(255) NOT NULL,
    operator character varying(255) DEFAULT NULL::character varying
);',
        'CREATE SEQUENCE public.game_transit_lines_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'ALTER SEQUENCE public.game_transit_lines_id_seq OWNED BY public.game_transit_lines.id;',
        'CREATE SEQUENCE public.game_transit_stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'CREATE TABLE public.game_transit_stations (
    id integer DEFAULT nextval(\'public.game_transit_stations_id_seq\'::regclass) NOT NULL,
    uuid character varying(36) NOT NULL,
    station_id character varying(128) NOT NULL,
    name character varying(200) DEFAULT NULL::character varying,
    point public.geography(Point,4326) NOT NULL,
    line_refs jsonb DEFAULT \'[]\'::jsonb NOT NULL,
    game_id integer NOT NULL
);',
        'CREATE TABLE public.games (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(120) NOT NULL,
    size character varying(1) NOT NULL,
    edition character varying(16) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    boundary_sw_lat double precision,
    boundary_sw_lng double precision,
    boundary_ne_lat double precision,
    boundary_ne_lng double precision,
    join_code character varying(6) DEFAULT NULL::bpchar,
    transit_tiles_path character varying(255) DEFAULT NULL::character varying,
    boundary_geo_json text,
    admin_levels json,
    possible_area_shared_with_hiders boolean DEFAULT true NOT NULL
);',
        'ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.gtfs_source (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    game_id integer,
    name character varying(200) NOT NULL,
    file_path character varying(500) NOT NULL,
    source_url character varying(1000) DEFAULT NULL::character varying,
    route_count integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);',
        'CREATE SEQUENCE public.gtfs_source_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'ALTER SEQUENCE public.gtfs_source_id_seq OWNED BY public.gtfs_source.id;',
        'CREATE TABLE public.hiding_zones (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    station_point public.geography(Point,4326) NOT NULL,
    radius_meters double precision NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    round_id integer NOT NULL,
    station_name character varying(255) DEFAULT NULL::character varying
);',
        'ALTER TABLE public.hiding_zones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hiding_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.player_locations (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    point public.geography(Point,4326) NOT NULL,
    recorded_at timestamp(0) without time zone NOT NULL,
    round_id integer NOT NULL,
    player_id integer NOT NULL,
    altitude double precision
);',
        'ALTER TABLE public.player_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.players (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    display_name character varying(80) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    game_id integer NOT NULL,
    left_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    password_hash character varying(255) NOT NULL
);',
        'ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.possible_area_constraints (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    round_id integer NOT NULL,
    geometry text NOT NULL,
    label character varying(100) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    label_key character varying(100) DEFAULT NULL::character varying,
    label_args json,
    source character varying(16) DEFAULT \'proven\'::character varying NOT NULL,
    mode character varying(16) DEFAULT NULL::character varying,
    draw_geometry text,
    created_by_membership_id integer
);',
        'CREATE SEQUENCE public.possible_area_constraints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;',
        'ALTER TABLE public.possible_area_constraints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.possible_area_constraints_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.round_memberships (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    side character varying(16) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    round_id integer NOT NULL,
    player_id integer NOT NULL
);',
        'ALTER TABLE public.round_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.round_street_networks (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    round_id integer NOT NULL,
    center public.geography(Point,4326) NOT NULL,
    radius_meters double precision NOT NULL,
    status character varying(16) NOT NULL,
    payload jsonb,
    way_count integer DEFAULT 0 NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    fetched_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);',
        'ALTER TABLE public.round_street_networks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_street_networks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.rounds (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    status character varying(16) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    game_id integer NOT NULL,
    hiding_period_started_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    hiding_period_ends_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    seeking_ended_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    endgame_started_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    banked_seeking_seconds integer DEFAULT 0 NOT NULL,
    in_move_period boolean DEFAULT false NOT NULL,
    bonus_minutes integer DEFAULT 0 NOT NULL,
    bonus_percent integer DEFAULT 0 NOT NULL,
    caught boolean DEFAULT false NOT NULL,
    hider_names json,
    trap_bonus_seconds integer DEFAULT 0 NOT NULL
);',
        'ALTER TABLE public.rounds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rounds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.seeker_candidate_markers (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    point public.geography(Point,4326) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    round_id integer NOT NULL,
    player_id integer NOT NULL
);',
        'ALTER TABLE public.seeker_candidate_markers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seeker_candidate_markers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'CREATE TABLE public.time_traps (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    round_id integer NOT NULL,
    placed_by_player_id integer NOT NULL,
    station_id integer NOT NULL,
    station_name character varying(200) DEFAULT NULL::character varying,
    point public.geography(Point,4326) NOT NULL,
    placed_at timestamp(0) without time zone NOT NULL,
    status character varying(16) NOT NULL,
    detected_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    detected_by_player_id integer,
    frozen_value_seconds integer,
    rearmed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    awarded_seconds integer
);',
        'ALTER TABLE public.time_traps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_traps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);',
        'ALTER TABLE ONLY public.game_gtfs_lines ALTER COLUMN id SET DEFAULT nextval(\'public.game_gtfs_lines_id_seq\'::regclass);',
        'ALTER TABLE ONLY public.game_transit_lines ALTER COLUMN id SET DEFAULT nextval(\'public.game_transit_lines_id_seq\'::regclass);',
        'ALTER TABLE ONLY public.gtfs_source ALTER COLUMN id SET DEFAULT nextval(\'public.gtfs_source_id_seq\'::regclass);',
        'ALTER TABLE ONLY public.asked_questions
    ADD CONSTRAINT asked_questions_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.chat_message_reads
    ADD CONSTRAINT chat_message_reads_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.features
    ADD CONSTRAINT features_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.game_areas
    ADD CONSTRAINT game_areas_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.game_gtfs_lines
    ADD CONSTRAINT game_gtfs_lines_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.game_transit_lines
    ADD CONSTRAINT game_transit_lines_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.game_transit_stations
    ADD CONSTRAINT game_transit_stations_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.gtfs_source
    ADD CONSTRAINT gtfs_source_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.hiding_zones
    ADD CONSTRAINT hiding_zones_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.player_locations
    ADD CONSTRAINT player_locations_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.possible_area_constraints
    ADD CONSTRAINT possible_area_constraints_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.round_memberships
    ADD CONSTRAINT round_memberships_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.round_street_networks
    ADD CONSTRAINT round_street_networks_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.seeker_candidate_markers
    ADD CONSTRAINT seeker_candidate_markers_pkey PRIMARY KEY (id);',
        'ALTER TABLE ONLY public.time_traps
    ADD CONSTRAINT time_traps_pkey PRIMARY KEY (id);',
        'CREATE INDEX idx_238edfbae48fd905 ON public.game_transit_lines USING btree (game_id);',
        'CREATE INDEX idx_264e43a6e48fd905 ON public.players USING btree (game_id);',
        'CREATE INDEX idx_27140d93726da211 ON public.asked_questions USING btree (asker_player_id);',
        'CREATE INDEX idx_2cdd8068d963622c ON public.game_gtfs_lines USING btree (gtfs_source_id);',
        'CREATE INDEX idx_2cdd8068e48fd905 ON public.game_gtfs_lines USING btree (game_id);',
        'CREATE INDEX idx_3a7fd554e48fd905 ON public.rounds USING btree (game_id);',
        'CREATE INDEX idx_6a83cbd3e48fd905 ON public.game_areas USING btree (game_id);',
        'CREATE INDEX idx_940c706e26fdf557 ON public.possible_area_constraints USING btree (created_by_membership_id);',
        'CREATE INDEX idx_b7ea7f8399e6f5df ON public.player_locations USING btree (player_id);',
        'CREATE INDEX idx_b7ea7f83a6005ca0 ON public.player_locations USING btree (round_id);',
        'CREATE INDEX idx_chat_question_uuid ON public.chat_messages USING btree (question_uuid);',
        'CREATE INDEX idx_chat_read_player ON public.chat_message_reads USING btree (player_id);',
        'CREATE INDEX idx_chat_reply_to_uuid ON public.chat_messages USING btree (reply_to_uuid);',
        'CREATE INDEX idx_d129781599e6f5df ON public.round_memberships USING btree (player_id);',
        'CREATE INDEX idx_d1297815a6005ca0 ON public.round_memberships USING btree (round_id);',
        'CREATE INDEX idx_dbb93e66e48fd905 ON public.gtfs_source USING btree (game_id);',
        'CREATE INDEX idx_ef20c9a6e48fd905 ON public.chat_messages USING btree (game_id);',
        'CREATE INDEX idx_ef20c9a6f624b39d ON public.chat_messages USING btree (sender_id);',
        'CREATE INDEX idx_feature_game_type ON public.features USING btree (game_id, feature_type);',
        'CREATE INDEX idx_location_round_player ON public.player_locations USING btree (round_id, player_id);',
        'CREATE INDEX idx_pac_round ON public.possible_area_constraints USING btree (round_id);',
        'CREATE INDEX idx_question_round ON public.asked_questions USING btree (round_id);',
        'CREATE INDEX idx_round_street_network_status ON public.round_street_networks USING btree (status);',
        'CREATE INDEX idx_scm_player ON public.seeker_candidate_markers USING btree (player_id);',
        'CREATE INDEX idx_scm_round ON public.seeker_candidate_markers USING btree (round_id);',
        'CREATE INDEX idx_time_trap_round ON public.time_traps USING btree (round_id);',
        'CREATE INDEX idx_transit_station_game ON public.game_transit_stations USING btree (game_id);',
        'CREATE UNIQUE INDEX uniq_238edfbad17f50a6 ON public.game_transit_lines USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_264e43a6d17f50a6 ON public.players USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_27140d93d17f50a6 ON public.asked_questions USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_2cdd8068d17f50a6 ON public.game_gtfs_lines USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_3a7fd554d17f50a6 ON public.rounds USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_639edb64a6005ca0 ON public.hiding_zones USING btree (round_id);',
        'CREATE UNIQUE INDEX uniq_639edb64d17f50a6 ON public.hiding_zones USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_6a83cbd3d17f50a6 ON public.game_areas USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_940c706ed17f50a6 ON public.possible_area_constraints USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_b7ea7f83d17f50a6 ON public.player_locations USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_bfc0dc13d17f50a6 ON public.features USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_chat_read_message_player ON public.chat_message_reads USING btree (message_id, player_id);',
        'CREATE UNIQUE INDEX uniq_d1297815d17f50a6 ON public.round_memberships USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_dbb93e66d17f50a6 ON public.gtfs_source USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_ef20c9a6d17f50a6 ON public.chat_messages USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_ff232b31d17f50a6 ON public.games USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_ff232b31e64d7d01 ON public.games USING btree (join_code);',
        'CREATE UNIQUE INDEX uniq_membership_round_player ON public.round_memberships USING btree (round_id, player_id);',
        'CREATE UNIQUE INDEX uniq_player_game_name ON public.players USING btree (game_id, display_name);',
        'CREATE UNIQUE INDEX uniq_round_street_network_round ON public.round_street_networks USING btree (round_id);',
        'CREATE UNIQUE INDEX uniq_round_street_network_uuid ON public.round_street_networks USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_scm_uuid ON public.seeker_candidate_markers USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_time_trap_uuid ON public.time_traps USING btree (uuid);',
        'CREATE UNIQUE INDEX uniq_transit_station_uuid ON public.game_transit_stations USING btree (uuid);',
        'ALTER TABLE ONLY public.players
    ADD CONSTRAINT fk_264e43a6e48fd905 FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.asked_questions
    ADD CONSTRAINT fk_27140d93726da211 FOREIGN KEY (asker_player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.asked_questions
    ADD CONSTRAINT fk_27140d93a6005ca0 FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT fk_3a7fd554e48fd905 FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.hiding_zones
    ADD CONSTRAINT fk_639edb64a6005ca0 FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.possible_area_constraints
    ADD CONSTRAINT fk_940c706e26fdf557 FOREIGN KEY (created_by_membership_id) REFERENCES public.round_memberships(id) ON DELETE SET NULL;',
        'ALTER TABLE ONLY public.player_locations
    ADD CONSTRAINT fk_b7ea7f8399e6f5df FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.player_locations
    ADD CONSTRAINT fk_b7ea7f83a6005ca0 FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.chat_message_reads
    ADD CONSTRAINT fk_chat_read_message FOREIGN KEY (message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.chat_message_reads
    ADD CONSTRAINT fk_chat_read_player FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.round_memberships
    ADD CONSTRAINT fk_d129781599e6f5df FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.round_memberships
    ADD CONSTRAINT fk_d1297815a6005ca0 FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_ef20c9a6e48fd905 FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_ef20c9a6f624b39d FOREIGN KEY (sender_id) REFERENCES public.players(id) ON DELETE SET NULL;',
        'ALTER TABLE ONLY public.features
    ADD CONSTRAINT fk_features_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.game_areas
    ADD CONSTRAINT fk_game_areas_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.game_gtfs_lines
    ADD CONSTRAINT fk_game_gtfs_lines_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.game_gtfs_lines
    ADD CONSTRAINT fk_game_gtfs_lines_source FOREIGN KEY (gtfs_source_id) REFERENCES public.gtfs_source(id) ON DELETE RESTRICT;',
        'ALTER TABLE ONLY public.game_transit_lines
    ADD CONSTRAINT fk_game_transit_lines_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.gtfs_source
    ADD CONSTRAINT fk_gtfs_source_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE SET NULL;',
        'ALTER TABLE ONLY public.possible_area_constraints
    ADD CONSTRAINT fk_pac_round FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.seeker_candidate_markers
    ADD CONSTRAINT fk_scm_player FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.seeker_candidate_markers
    ADD CONSTRAINT fk_scm_round FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.game_transit_stations
    ADD CONSTRAINT fk_transit_station_game FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.round_street_networks
    ADD CONSTRAINT round_street_networks_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.time_traps
    ADD CONSTRAINT time_traps_detected_by_player_id_fkey FOREIGN KEY (detected_by_player_id) REFERENCES public.players(id) ON DELETE SET NULL;',
        'ALTER TABLE ONLY public.time_traps
    ADD CONSTRAINT time_traps_placed_by_player_id_fkey FOREIGN KEY (placed_by_player_id) REFERENCES public.players(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.time_traps
    ADD CONSTRAINT time_traps_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;',
        'ALTER TABLE ONLY public.time_traps
    ADD CONSTRAINT time_traps_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.game_transit_stations(id) ON DELETE CASCADE;',
    ];

    public function getDescription(): string
    {
        return 'Consolidated initial schema baseline: games, players, rounds, locations, chat, questions, zones, transit and street networks (single baseline replacing the migration history).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS postgis');
        foreach (self::SCHEMA_SQL as $sql) {
            $this->addSql($sql);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS asked_questions, chat_message_reads, chat_messages, features, game_areas, game_gtfs_lines, game_transit_lines, game_transit_stations, games, gtfs_source, hiding_zones, player_locations, players, possible_area_constraints, round_memberships, round_street_networks, rounds, seeker_candidate_markers, time_traps CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS features_id_seq, game_areas_id_seq, game_transit_stations_id_seq, possible_area_constraints_id_seq CASCADE');
    }
}
